language: ruby

branches:
  only:
    - master

rvm:
  - 1.9.3

before_script:
  - wget --no-check-certificate -O tests/roundup https://raw.github.com/bmizerany/roundup/a8a175a7fba9bbfb14d1025951c4b46a65e875a6/roundup.sh
  - chmod +x tests/roundup

script:
  - rake spec
  - cd tests && ./roundup

gemfile: .gemfile
